"""updated tables

Revision ID: 0e9e4e87521e
Revises: 0001
Create Date: 2026-02-11 15:02:04.042544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0e9e4e87521e'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote', sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_constraint('vote_user_id_fkey', 'vote', type_='foreignkey')
    op.drop_column('vote', 'title')
    op.drop_column('vote', 'description')
    op.drop_column('vote', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('vote', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('vote', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('vote_user_id_fkey', 'vote', 'user', ['user_id'], ['id'])
    op.drop_column('vote', 'role')
    # ### end Alembic commands ###
