"""add campaign ctv_session interaction tables

Revision ID: 676d2c3318fd
Revises: 0e9e4e87521e
Create Date: 2026-02-12 10:19:31.058047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '676d2c3318fd'
down_revision: Union[str, None] = '0e9e4e87521e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('qr_base_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('interaction_config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_name'), 'campaign', ['name'], unique=False)
    op.create_table('ctvsession',
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('pairing_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('waiting_for_pair', 'paired', 'expired', 'closed', name='sessionstatus'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('paired_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ctvsession_pairing_code'), 'ctvsession', ['pairing_code'], unique=False)
    op.create_table('interaction',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('action_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['ctvsession.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interaction')
    op.drop_index(op.f('ix_ctvsession_pairing_code'), table_name='ctvsession')
    op.drop_table('ctvsession')
    op.drop_index(op.f('ix_campaign_name'), table_name='campaign')
    op.drop_table('campaign')
    # ### end Alembic commands ###
